name: Create Python Artifacts

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:  # Trigger on pull requests

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"  # Specify the Python version

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run your Python script or build process
    - name: Build project
      run: |
        python setup.py sdist bdist_wheel  # Example for packaging a Python project

    # Step 5: Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v4.6.1
      with:
        name: python-artifacts
        path: dist/  # Path to the build artifacts
